apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-cicd-deploy
  namespace: fastapi-cicd-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-cicd
  template:
    metadata:
      labels:
        app: fastapi-cicd
    spec:
      containers:
        - name: fastapi-cicd
          image: us-central1-docker.pkg.dev/test-teraform-vm/fastapi-repo/fastapi-cicd-demo:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20

