name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  PROJECT_ID: test-teraform-vm
  REGION: us-central1
  CLUSTER_NAME: fastapi-gke-cluster
  IMAGE: us-central1-docker.pkg.dev/test-teraform-vm/fastapi-repo/fastapi-cicd-demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1️⃣ Checkout Code
        uses: actions/checkout@v4

      - name: 2️⃣ Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 3️⃣ Install Dependencies
        run: |
          cd app
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: 4️⃣ Run Unit Tests
        run: |
          cd app
          pytest --maxfail=1 --disable-warnings -q

      - name: 5️⃣ Run Linting (Flake8)
        run: |
          pip install flake8
          flake8 app --max-line-length=120

      - name: 6️⃣ Run Security Scan (Bandit)
        run: |
          pip install bandit
          bandit -r app

      - name: 7️⃣ Build and Push Docker Image
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
          docker build -t $IMAGE:${{ github.run_number }} .
          docker push $IMAGE:${{ github.run_number }}
          echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

      - name: 8️⃣ Deploy to GKE
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $REGION-a --project $PROJECT_ID
          kubectl set image deployment/fastapi-cicd-deploy fastapi-cicd=$IMAGE:${{ github.run_number }} -n fastapi-cicd-ns
          kubectl rollout status deployment/fastapi-cicd-deploy -n fastapi-cicd-ns

