name: CI-CD Pipeline for FastAPI on GKE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: fastapi-gke-project
  REGION: us-central1
  CLUSTER_NAME: fastapi-gke-cluster
  CLUSTER_ZONE: us-central1-c
  IMAGE: fastapi-cicd-app
  IMAGE_TAG: latest
  DEPLOYMENT_NAME: fastapi-cicd-deploy
  NAMESPACE: fastapi-cicd-ns

jobs:
  # 1️⃣ Checkout Code
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  # 2️⃣ Lint
  lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install flake8
          flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics || true

  # 3️⃣ Unit Tests
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          pip install -r requirements.txt
          pip install pytest
          pytest || true

  # 4️⃣ Build Docker Image
  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      image_name: ${{ steps.set_image.outputs.image_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }} .
      
      - name: Save image name
        id: set_image
        run: echo "image_name=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

  # 5️⃣ Push Docker Image to GCR
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet
      - name: Push image to GCR
        run: |
          docker push ${{ needs.build.outputs.image_name }}

  # 6️⃣ Deploy to GKE
  deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }} --project ${{ env.PROJECT_ID }}
      - run: |
          kubectl -n ${{ env.NAMESPACE }} set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=${{ needs.build.outputs.image_name }} --record
          kubectl -n ${{ env.NAMESPACE }} rollout status deployment/${{ env.DEPLOYMENT_NAME }}

  # 7️⃣ Verify Deployment
  verify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }} --project ${{ env.PROJECT_ID }}
      - run: |
          echo "Deployment verification started..."
          kubectl -n ${{ env.NAMESPACE }} get pods
          kubectl -n ${{ env.NAMESPACE }} get svc
          EXTERNAL_IP=$(kubectl -n ${{ env.NAMESPACE }} get svc ${{ env.DEPLOYMENT_NAME }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "✅ FastAPI successfully deployed! External IP: $EXTERNAL_IP"
          curl -I http://$EXTERNAL_IP

  # 8️⃣ Notify
  notify:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - run: |
          echo "🎉 CI/CD pipeline completed successfully!"

