name: CI/CD Pipeline for FastAPI on GKE

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: fastapi-gke-project
  REGION: us-central1
  REPOSITORY: fastapi-repo
  IMAGE_NAME: fastapi-cicd-app
  CLUSTER_NAME: fastapi-gke-cluster
  NAMESPACE: fastapi-cicd-ns

jobs:
  1️⃣-checkout:
    name: 🧩 Step 1 - Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  2️⃣-setup-python:
    name: 🐍 Step 2 - Setup Python
    runs-on: ubuntu-latest
    needs: [1️⃣-checkout]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  3️⃣-run-tests:
    name: 🧪 Step 3 - Run Tests
    runs-on: ubuntu-latest
    needs: [2️⃣-setup-python]
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: pytest || echo "No tests found, skipping"

  4️⃣-build-image:
    name: 🐳 Step 4 - Build Docker Image
    runs-on: ubuntu-latest
    needs: [3️⃣-run-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: "gke-gcloud-auth-plugin"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} .
          docker save ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} -o image.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  5️⃣-push-image:
    name: 🚀 Step 5 - Push Docker Image to Artifact Registry
    runs-on: ubuntu-latest
    needs: [4️⃣-build-image]
    steps:
      - name: Download built image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Load and Push Docker Image
        run: |
          docker load -i image.tar
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          echo "✅ Docker image pushed successfully."

  6️⃣-deploy-gke:
    name: ☸️ Step 6 - Deploy to GKE
    runs-on: ubuntu-latest
    needs: [5️⃣-push-image]
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: "gke-gcloud-auth-plugin"

      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --region ${{ env.REGION }} --project ${{ env.PROJECT_ID }}

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/${{ env.IMAGE_NAME }} -n ${{ env.NAMESPACE }}

  7️⃣-verify-deploy:
    name: 🔍 Step 7 - Verify Deployment
    runs-on: ubuntu-latest
    needs: [6️⃣-deploy-gke]
    steps:
      - name: Check service status
        run: kubectl -n ${{ env.NAMESPACE }} get svc

  8️⃣-cleanup:
    name: 🧹 Step 8 - Cleanup (Optional)
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Cleanup workspace
        run: rm -rf *

