name: CI-CD Pipeline for FastAPI on GKE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: fastapi-gke-project        # 🔹 Change to your GCP project ID
  REGION: us-central1
  CLUSTER_NAME: fastapi-gke-cluster      # 🔹 Change to your GKE cluster name
  CLUSTER_ZONE: us-central1-c
  IMAGE: fastapi-cicd-app
  IMAGE_TAG: latest
  DEPLOYMENT_NAME: fastapi-cicd-deploy
  NAMESPACE: fastapi-cicd-ns

jobs:
  # 1️⃣ Checkout Code
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  # 2️⃣ Linting
  lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run linting with flake8
        run: |
          pip install flake8
          flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics || true

  # 3️⃣ Unit Testing
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest || true

  # 4️⃣ Build Docker Image
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }} .

      - name: Save image name
        run: echo "IMAGE_NAME=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

  # 5️⃣ Push Image to Google Artifact Registry / GCR
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker --quiet

      - name: Push image
        run: |
          docker push ${{ env.IMAGE_NAME }}

  # 6️⃣ Deploy to GKE
  deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --zone ${{ env.CLUSTER_ZONE }} \
            --project ${{ env.PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl -n ${{ env.NAMESPACE }} set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=${{ env.IMAGE_NAME }} --record
          kubectl -n ${{ env.NAMESPACE }} rollout status deployment/${{ env.DEPLOYMENT_NAME }}

  # 7️⃣ Post-Deployment Verification
  verify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet
          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --zone ${{ env.CLUSTER_ZONE }} \
            --project ${{ env.PROJECT_ID }}

      - name: Verify Application Deployment
        run: |
          echo "Deployment verification started..."
          kubectl -n ${{ env.NAMESPACE }} get pods
          kubectl -n ${{ env.NAMESPACE }} get svc
          EXTERNAL_IP=$(kubectl -n ${{ env.NAMESPACE }} get svc ${{ env.DEPLOYMENT_NAME }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "✅ FastAPI successfully deployed! External IP: $EXTERNAL_IP"
          echo "Checking endpoint..."
          curl -I http://$EXTERNAL_IP

  # 8️⃣ Notification
  notify:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Success Notification
        run: |
          echo "🎉 CI/CD pipeline executed successfully!"
          echo "Application deployed and verified on GKE."

